In [1]:
2 ** 1000

10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376

In [2]:
import numpy as np

In [3]:
np.int64(2) ** 1000

/Users/mikitebeka/anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: overflow encountered in long_scalars
  if __name__ == '__main__':


0

In [4]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
len(arr)

3

In [6]:
arr[1]

2

In [7]:
type(arr[1])

numpy.int64

In [8]:
arr.dtype

dtype('int64')

In [9]:
arr32 = np.array([1,2,3], dtype=np.int32)
arr32

array([1, 2, 3], dtype=int32)

In [10]:
arr * arr

array([1, 4, 9])

In [11]:
v1 = np.random.rand(1000000)
v2 = np.random.rand(1000000)

In [12]:
%time v1 * v2

CPU times: user 2.95 ms, sys: 3.23 ms, total: 6.18 ms
Wall time: 4.75 ms


array([ 0.22068702,  0.05988467,  0.25420964, ...,  0.00383288,
        0.13383574,  0.40781362])

In [13]:
np.dot(arr, arr)

14

In [14]:
arr @ arr

14

In [15]:
mat = np.array([[1,2,3], [4,5,6], [7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
v = np.arange(12)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
v.reshape((4, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
mat = np.arange(12).reshape((4, 3))
mat

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
mat.shape

(4, 3)

In [20]:
mat2 = mat.reshape((3, 4))
mat2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
mat[1,2] = 17

In [22]:
mat2

array([[ 0,  1,  2,  3],
       [ 4, 17,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
nums = [1,2,3,4,5]
nums[2:4]

[3, 4]

In [24]:
v = np.arange(1, 6)
v[2:4]

array([3, 4])

In [25]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
arr[0]

array([0, 1, 2, 3])

In [27]:
arr[1, 1]

5

In [28]:
arr[1,1]

5

In [29]:
arr[:, 1]

array([1, 5, 9])

In [30]:
arr[:,1].reshape((3, 1))

array([[1],
       [5],
       [9]])

In [31]:
arr[1:, 2:]

array([[ 6,  7],
       [10, 11]])

In [32]:
arr[1:, 2:] = 7
arr

array([[0, 1, 2, 3],
       [4, 5, 7, 7],
       [8, 9, 7, 7]])

In [33]:
arr = np.arange(3)

In [34]:
arr[np.array([True, False, True])]

array([0, 2])

In [35]:
arr >= 1

array([False,  True,  True], dtype=bool)

In [36]:
arr[arr>=1]

array([1, 2])

In [37]:
arr = np.arange(10)

In [38]:
arr[(arr>2)&(arr<7)]

array([3, 4, 5, 6])

In [39]:
arr[(arr>7)|(arr<2)]

array([0, 1, 8, 9])

In [40]:
arr[~(arr>7)]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [41]:
mat = np.random.rand(5, 5)
mat

array([[ 0.1297194 ,  0.38704379,  0.54038282,  0.20343936,  0.10577855],
       [ 0.1697811 ,  0.63104017,  0.22566152,  0.9413238 ,  0.7867378 ],
       [ 0.30604622,  0.77748133,  0.28552089,  0.11966891,  0.52002642],
       [ 0.53832172,  0.16164886,  0.21151739,  0.45513661,  0.71627705],
       [ 0.40089507,  0.476247  ,  0.30931114,  0.87782206,  0.73601762]])

In [42]:
mat[np.abs(mat - mat.mean()) > 1.5*mat.std()]

array([ 0.9413238 ,  0.87782206])

In [43]:
np.abs(mat - mat.mean())

array([[ 0.31079447,  0.05347007,  0.09986896,  0.2370745 ,  0.33473532],
       [ 0.27073276,  0.19052631,  0.21485234,  0.50080994,  0.34622393],
       [ 0.13446765,  0.33696747,  0.15499298,  0.32084496,  0.07951255],
       [ 0.09780785,  0.278865  ,  0.22899648,  0.01462275,  0.27576318],
       [ 0.0396188 ,  0.03573314,  0.13120272,  0.4373082 ,  0.29550376]])

In [44]:
np.abs(mat - mat.mean()) > 1.5*mat.std()

array([[False, False, False, False, False],
       [False, False, False,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True, False]], dtype=bool)

In [45]:
mat[np.abs(mat - mat.mean()) > 1.5*mat.std()]

array([ 0.9413238 ,  0.87782206])

In [46]:
mat[np.abs(mat - mat.mean()) > 1.5*mat.std()] = mat.mean()

In [47]:
arr = np.arange(3)
arr + 4

array([4, 5, 6])

In [48]:
arr / 7

array([ 0.        ,  0.14285714,  0.28571429])

In [49]:
arr ** 2

array([0, 1, 4])

In [50]:
mat = np.arange(9).reshape((3, 3))
vec = np.arange(3)

In [51]:
mat + vec

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [52]:
v1 = np.arange(3)
v2 = np.arange(3).reshape((3, 1))

In [53]:
v2

array([[0],
       [1],
       [2]])

In [54]:
v2.shape

(3, 1)

In [55]:
v1 + v2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [56]:
np.arange(3) + np.arange(4)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [57]:
v = np.arange(12).reshape((4, 3))

In [58]:
dir(v)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',

In [59]:
v.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [60]:
v.any()

True

In [61]:
v.all()

False

In [62]:
if v:
    print('v is True')

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [63]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [64]:
v.prod()

0

In [65]:
v.sum(axis=1)

array([ 3, 12, 21, 30])

In [66]:
v.sum(axis=0)

array([18, 22, 26])

In [67]:
v1 = v.copy()

In [68]:
v1[0,0] = 1000
v

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [69]:
data = v.dumps()
data

b'\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x04K\x03\x86q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00i8q\x0cK\x00K\x01\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89h\x03X`\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\t\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\x0b\x00\x00\x00\x00\x00\x00\x00q\x11h\x05\x86q\x12Rq\x13tq\x14b.'

In [70]:
v2 = np.loads(data)
v2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])